const ventas =[{
    id: 1,    
    kind: "Duplex",
    rent: true,
    sell: true,
    temporal: false,
    rent_price: 150000,
    sell_price: 52000,
    temporal_price: "consultar",
    rent_coin: '$',
    sell_coin: 'USD',
    temporal_coin: '',
    titles: ["DÚPLEX EN VENTA", "EN VALLE CERCANO.", "INCREIBLE"],
    province: 'CORDOBA',
    city: 'CAPITAL',
    neighborhood: "valle cercano",
    age: 'A estrenar',
    rooms: 3,
    bedrooms: 2,
    bathrooms: 1,
    garage: true,
    images:['https://federicorizzo.com.ar/wp-content/uploads/2023/11/Frente-277.jpg',
            'https://federicorizzo.com.ar/wp-content/uploads/2023/11/Frente-276.jpg',
            'https://federicorizzo.com.ar/wp-content/uploads/2023/11/Frente-278.jpg',
            'https://federicorizzo.com.ar/wp-content/uploads/2023/11/Frente-279.jpg',
            'https://federicorizzo.com.ar/wp-content/uploads/2023/11/Frente-280.jpg',
            'https://federicorizzo.com.ar/wp-content/uploads/2023/11/Frente-281.jpg',
            'https://federicorizzo.com.ar/wp-content/uploads/2023/11/Frente-282.jpg',
            'https://federicorizzo.com.ar/wp-content/uploads/2023/11/Frente-284.jpg',
            'https://federicorizzo.com.ar/wp-content/uploads/2023/11/Frente-285.jpg'],
    opportunities: true,
},{
    id: 2,    
    kind: "Departamento",
    rent: true,
    sell: true,
    temporal: false,
    rent_price: 80000,
    sell_price: 45000,
    temporal_price: "consultar",
    rent_coin: '$',
    sell_coin: 'USD',
    temporal_coin: '',
    titles: ["FINANCIACION UNICA.", "DPTO EN VENTA.", "CALLE MÉXICO 1105. 1 DORM."],
    province: 'CORDOBA',
    city: 'CAPITAL',
    neighborhood: 'Alta Córdoba',
    age: 'Entre 5 y 10 años',
    rooms: 3,
    bedrooms: 1,
    bathrooms: 1,
    garage: false,
    images:['https://federicorizzo.com.ar/wp-content/uploads/2023/11/Frente-898.jpg',
            'https://federicorizzo.com.ar/wp-content/uploads/2023/11/Frente-900.jpg',
            'https://federicorizzo.com.ar/wp-content/uploads/2023/11/Frente-899.jpg',
            'https://federicorizzo.com.ar/wp-content/uploads/2023/11/Frente-904.jpg',
            'https://federicorizzo.com.ar/wp-content/uploads/2023/11/Frente-902.jpg',
            'https://federicorizzo.com.ar/wp-content/uploads/2023/11/Frente-901.jpg',
            'https://federicorizzo.com.ar/wp-content/uploads/2023/11/Frente-903.jpg',],
    opportunities: true,
},{
    id: 3,    
    kind: "Casa",
    rent: false,
    sell: true,
    temporal: false,
    rent_price: 120000,
    sell_price: 110000,
    temporal_price: "consultar",
    rent_coin: '$',
    sell_coin: 'USD',
    temporal_coin: '',
    titles: ["ESPECTACULAR DÚPLEX", "PRADOS DE MANANTIALES.", "A ESTRENAR."],
    province: 'CORDOBA',
    city: 'CAPITAL',
    neighborhood: 'Manantiales II',
    age: 'A estrenar',
    rooms: 4,
    bedrooms: 3,
    bathrooms: 2,
    garage: true,
    images:['https://federicorizzo.com.ar/wp-content/uploads/2023/11/Frente-818-scaled.jpg',
            'https://federicorizzo.com.ar/wp-content/uploads/2023/11/Frente-799-scaled.jpg',
            'https://federicorizzo.com.ar/wp-content/uploads/2023/11/Frente-802-scaled.jpg',
            'https://federicorizzo.com.ar/wp-content/uploads/2023/11/Frente-807-scaled.jpg',
            'https://federicorizzo.com.ar/wp-content/uploads/2023/11/Frente-804-scaled.jpg',
            'https://federicorizzo.com.ar/wp-content/uploads/2023/11/Frente-806-scaled.jpg',
            'https://federicorizzo.com.ar/wp-content/uploads/2023/11/Frente-811-scaled.jpg',
            'https://federicorizzo.com.ar/wp-content/uploads/2023/11/Frente-809-scaled.jpg',
            'https://federicorizzo.com.ar/wp-content/uploads/2023/11/Frente-816-scaled.jpg',
            'https://federicorizzo.com.ar/wp-content/uploads/2023/11/Frente-814-scaled.jpg',
            'https://federicorizzo.com.ar/wp-content/uploads/2023/11/Frente-817-scaled.jpg',
            'https://federicorizzo.com.ar/wp-content/uploads/2023/11/Frente-820-1-scaled.jpg',
            ],
    opportunities: true,
}]

export default ventas